# Generated by Django 6.0.6 on 2026-06-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajero', models.CharField(max_length=150)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('turno_descripcion', models.CharField(max_length=200)),
                ('fondo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_efectivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_qr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efectivo_contado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('detalle_movimientos', models.JSONField(blank=True, default=list)),
                ('detalle_efectivo', models.JSONField(blank=True, default=dict)),
                ('archivado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reporte de Cierre de Caja',
                'verbose_name_plural': 'Reportes de Cierre de Caja',
            },
        ),
    ]
